// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using talim_platforma.Data;

#nullable disable

namespace talim_platforma.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251019010927_AddGuruhTable")]
    partial class AddGuruhTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("talim_platforma.Models.Baho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ball")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DarsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImtihonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DarsId");

                    b.HasIndex("ImtihonId");

                    b.HasIndex("TalabaId");

                    b.ToTable("Baholar");
                });

            modelBuilder.Entity("talim_platforma.Models.Dars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DarsTuri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Davomiylik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuruhId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mavzu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OqituvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuruhId");

                    b.HasIndex("OqituvchiId");

                    b.ToTable("Darslar");
                });

            modelBuilder.Entity("talim_platforma.Models.Davomat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuruhId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Holati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<int>("OqituvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DarsId");

                    b.HasIndex("GuruhId");

                    b.HasIndex("OqituvchiId");

                    b.HasIndex("TalabaId");

                    b.ToTable("Davomatlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Foydalanuvchi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Familiya")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ism")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtasiningIsmi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonRaqam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Foydalanuvchilar");
                });

            modelBuilder.Entity("talim_platforma.Models.FoydalanuvchiToliqMalumoti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoydalanuvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manzil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QarindoshFamilyasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QarindoshIsmi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QarindoshTelefonRaqami")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QarindoshlikDarajasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoydalanuvchiId")
                        .IsUnique();

                    b.ToTable("FoydalanuvchiToliqMalumotlari");
                });

            modelBuilder.Entity("talim_platforma.Models.Guruh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BoshlanishSanasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DarsKunlari")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DarsVaqti")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoydalanuvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Holati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OqituvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Xona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoydalanuvchiId");

                    b.HasIndex("KursId");

                    b.HasIndex("OqituvchiId");

                    b.ToTable("Guruhlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Imtihon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoshlanishVaqti")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuruhId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImtihonTuri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Izoh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OqituvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<string>("TugashVaqti")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuruhId");

                    b.HasIndex("OqituvchiId");

                    b.ToTable("Imtihonlar");
                });

            modelBuilder.Entity("talim_platforma.Models.ImtihonNatija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FoizNatija")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImtihonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Otdimi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UmumiyBall")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImtihonId");

                    b.HasIndex("TalabaId");

                    b.ToTable("ImtihonNatijalar");
                });

            modelBuilder.Entity("talim_platforma.Models.ImtihonSavol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallQiymati")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImtihonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavolMatni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TogriJavob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImtihonId");

                    b.ToTable("ImtihonSavollar");
                });

            modelBuilder.Entity("talim_platforma.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Darajasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Narxi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tavsif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kurslar");
                });

            modelBuilder.Entity("talim_platforma.Models.TalabaGuruh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuruhId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QoshilganSana")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuruhId");

                    b.HasIndex("TalabaId");

                    b.ToTable("TalabaGuruhlar");
                });

            modelBuilder.Entity("talim_platforma.Models.TalabaKurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Holati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QoshilganSana")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("TalabaId");

                    b.ToTable("TalabaKurslar");
                });

            modelBuilder.Entity("talim_platforma.Models.Tolov", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Holati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Summa")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TolovSana")
                        .HasColumnType("TEXT");

                    b.Property<string>("TolovTuri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("TalabaId");

                    b.ToTable("Tolovlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Baho", b =>
                {
                    b.HasOne("talim_platforma.Models.Dars", "Dars")
                        .WithMany()
                        .HasForeignKey("DarsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("talim_platforma.Models.Imtihon", "Imtihon")
                        .WithMany()
                        .HasForeignKey("ImtihonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dars");

                    b.Navigation("Imtihon");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.Dars", b =>
                {
                    b.HasOne("talim_platforma.Models.Guruh", "Guruh")
                        .WithMany("Darslar")
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Oqituvchi")
                        .WithMany()
                        .HasForeignKey("OqituvchiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guruh");

                    b.Navigation("Oqituvchi");
                });

            modelBuilder.Entity("talim_platforma.Models.Davomat", b =>
                {
                    b.HasOne("talim_platforma.Models.Dars", "Dars")
                        .WithMany()
                        .HasForeignKey("DarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Guruh", "Guruh")
                        .WithMany("Davomatlar")
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Oqituvchi")
                        .WithMany("OqituvchiDavomatlar")
                        .HasForeignKey("OqituvchiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany("TalabaDavomatlar")
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dars");

                    b.Navigation("Guruh");

                    b.Navigation("Oqituvchi");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.FoydalanuvchiToliqMalumoti", b =>
                {
                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Foydalanuvchi")
                        .WithOne("FoydalanuvchiToliqMalumoti")
                        .HasForeignKey("talim_platforma.Models.FoydalanuvchiToliqMalumoti", "FoydalanuvchiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foydalanuvchi");
                });

            modelBuilder.Entity("talim_platforma.Models.Guruh", b =>
                {
                    b.HasOne("talim_platforma.Models.Foydalanuvchi", null)
                        .WithMany("Guruhlar")
                        .HasForeignKey("FoydalanuvchiId");

                    b.HasOne("talim_platforma.Models.Kurs", "Kurs")
                        .WithMany("Guruhlar")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Oqituvchi")
                        .WithMany()
                        .HasForeignKey("OqituvchiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Oqituvchi");
                });

            modelBuilder.Entity("talim_platforma.Models.Imtihon", b =>
                {
                    b.HasOne("talim_platforma.Models.Guruh", "Guruh")
                        .WithMany()
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Oqituvchi")
                        .WithMany()
                        .HasForeignKey("OqituvchiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guruh");

                    b.Navigation("Oqituvchi");
                });

            modelBuilder.Entity("talim_platforma.Models.ImtihonNatija", b =>
                {
                    b.HasOne("talim_platforma.Models.Imtihon", "Imtihon")
                        .WithMany()
                        .HasForeignKey("ImtihonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imtihon");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.ImtihonSavol", b =>
                {
                    b.HasOne("talim_platforma.Models.Imtihon", "Imtihon")
                        .WithMany("Savollar")
                        .HasForeignKey("ImtihonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imtihon");
                });

            modelBuilder.Entity("talim_platforma.Models.TalabaGuruh", b =>
                {
                    b.HasOne("talim_platforma.Models.Guruh", "Guruh")
                        .WithMany("TalabaGuruhlar")
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guruh");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.TalabaKurs", b =>
                {
                    b.HasOne("talim_platforma.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.Tolov", b =>
                {
                    b.HasOne("talim_platforma.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.Foydalanuvchi", b =>
                {
                    b.Navigation("FoydalanuvchiToliqMalumoti");

                    b.Navigation("Guruhlar");

                    b.Navigation("OqituvchiDavomatlar");

                    b.Navigation("TalabaDavomatlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Guruh", b =>
                {
                    b.Navigation("Darslar");

                    b.Navigation("Davomatlar");

                    b.Navigation("TalabaGuruhlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Imtihon", b =>
                {
                    b.Navigation("Savollar");
                });

            modelBuilder.Entity("talim_platforma.Models.Kurs", b =>
                {
                    b.Navigation("Guruhlar");
                });
#pragma warning restore 612, 618
        }
    }
}
