// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using talim_platforma.Data;

#nullable disable

namespace talim_platforma.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251211160000_AddAdvertisements")]
    partial class AddAdvertisements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("talim_platforma.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("talim_platforma.Models.Baho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ball")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DarsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImtihonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DarsId");

                    b.HasIndex("ImtihonId");

                    b.HasIndex("TalabaId");

                    b.ToTable("Baholar");
                });

            modelBuilder.Entity("talim_platforma.Models.Dars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DarsTuri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Davomiylik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuruhId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mavzu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OqituvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuruhId");

                    b.HasIndex("OqituvchiId");

                    b.ToTable("Darslar");
                });

            modelBuilder.Entity("talim_platforma.Models.Davomat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuruhId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Holati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<int>("OqituvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DarsId");

                    b.HasIndex("GuruhId");

                    b.HasIndex("OqituvchiId");

                    b.HasIndex("TalabaId");

                    b.ToTable("Davomatlar");
                });

            modelBuilder.Entity("talim_platforma.Models.DavomatSabab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DavomatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sabab")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DavomatId");

                    b.HasIndex("TalabaId");

                    b.ToTable("DavomatSabablar");
                });

            modelBuilder.Entity("talim_platforma.Models.Foydalanuvchi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Familiya")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Faolmi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ism")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OxirgiKirishVaqti")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonRaqam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YangilanganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Foydalanuvchilar");
                });

            modelBuilder.Entity("talim_platforma.Models.FoydalanuvchiToliqMalumoti", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FISH")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuruhNomi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KursNomi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OxirgiYangilanish")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportRaqami")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportSeriya")
                        .HasColumnType("TEXT");

                    b.Property<string>("Viloyat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoydalanuvchiToliqMalumotlari");
                });

            modelBuilder.Entity("talim_platforma.Models.Guruh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DarsKunlari")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DarsVaqti")
                        .HasColumnType("TEXT");

                    b.Property<string>("Holati")
                        .HasColumnType("TEXT");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OqituvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Xona")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("OqituvchiId");

                    b.ToTable("Guruhlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Imtihon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoshlanishVaqti")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Faolmi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuruhId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImtihonFormati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImtihonTuri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OqituvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<string>("TugashVaqti")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimalBall")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MuddatDaqiqada")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SertifikatBeriladimi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuruhId");

                    b.HasIndex("OqituvchiId");

                    b.ToTable("Imtihonlar");
                });

            modelBuilder.Entity("talim_platforma.Models.ImtihonNatija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ballar")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BoshlanishVaqti")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<string>("JavoblarJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImtihonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImtihonId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaksimalBall")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Otdimi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sana")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TugashVaqti")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UmumiyBall")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoizNatija")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImtihonId");

                    b.HasIndex("ImtihonId1");

                    b.HasIndex("TalabaId");

                    b.ToTable("ImtihonNatijalar");
                });

            modelBuilder.Entity("talim_platforma.Models.ImtihonSavol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ball")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JavoblarJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImtihonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavolMatni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TogriJavob")
                        .HasColumnType("TEXT");

                    b.Property<string>("Turi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImtihonId");

                    b.ToTable("ImtihonSavollar");
                });

            modelBuilder.Entity("talim_platforma.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Kunduzgi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Kechki")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Narxi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SertifikatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soni")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SertifikatId");

                    b.ToTable("Kurslar");
                });

            modelBuilder.Entity("talim_platforma.Models.Qurilma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OxirgiFoydalanish")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platforma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FoydalanuvchiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoydalanuvchiId");

                    b.ToTable("Qurilmalar");
                });

            modelBuilder.Entity("talim_platforma.Models.Sertifikat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BerilganSana")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImtihonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SertifikatNomi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SertifikatRaqami")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImtihonId");

                    b.HasIndex("KursId");

                    b.HasIndex("TalabaId");

                    b.ToTable("Sertifikatlar");
                });

            modelBuilder.Entity("talim_platforma.Models.TalabaGuruh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QoshilganSana")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuruhId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuruhId");

                    b.HasIndex("TalabaId");

                    b.ToTable("TalabaGuruhlar");
                });

            modelBuilder.Entity("talim_platforma.Models.TalabaKurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktivmi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Holati")
                        .HasColumnType("TEXT");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("TalabaId");

                    b.ToTable("TalabaKurslar");
                });

            modelBuilder.Entity("talim_platforma.Models.Tolov", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChegirmaFoiz")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChekRaqami")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Haqdorlik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Holat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Miqdor")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Qarzdorlik")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TalabaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalabaKursId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TolovUsuli")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YaratilganVaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("TalabaId");

                    b.HasIndex("TalabaKursId");

                    b.ToTable("Tolovlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Qurilma", b =>
                {
                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Foydalanuvchi")
                        .WithMany()
                        .HasForeignKey("FoydalanuvchiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foydalanuvchi");
                });

            modelBuilder.Entity("talim_platforma.Models.Baho", b =>
                {
                    b.HasOne("talim_platforma.Models.Dars", "Dars")
                        .WithMany()
                        .HasForeignKey("DarsId");

                    b.HasOne("talim_platforma.Models.Imtihon", "Imtihon")
                        .WithMany()
                        .HasForeignKey("ImtihonId");

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dars");

                    b.Navigation("Imtihon");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.Dars", b =>
                {
                    b.HasOne("talim_platforma.Models.Guruh", "Guruh")
                        .WithMany("Darslar")
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Oqituvchi")
                        .WithMany()
                        .HasForeignKey("OqituvchiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guruh");

                    b.Navigation("Oqituvchi");
                });

            modelBuilder.Entity("talim_platforma.Models.Davomat", b =>
                {
                    b.HasOne("talim_platforma.Models.Dars", "Dars")
                        .WithMany()
                        .HasForeignKey("DarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Guruh", "Guruh")
                        .WithMany("Davomatlar")
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Oqituvchi")
                        .WithMany("OqituvchiDavomatlar")
                        .HasForeignKey("OqituvchiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany("TalabaDavomatlar")
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dars");

                    b.Navigation("Guruh");

                    b.Navigation("Oqituvchi");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.DavomatSabab", b =>
                {
                    b.HasOne("talim_platforma.Models.Davomat", "Davomat")
                        .WithMany()
                        .HasForeignKey("DavomatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Davomat");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.Foydalanuvchi", b =>
                {
                    b.HasOne("talim_platforma.Models.FoydalanuvchiToliqMalumoti", "FoydalanuvchiToliqMalumoti")
                        .WithOne("Foydalanuvchi")
                        .HasForeignKey("talim_platforma.Models.FoydalanuvchiToliqMalumoti", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoydalanuvchiToliqMalumoti");
                });

            modelBuilder.Entity("talim_platforma.Models.Guruh", b =>
                {
                    b.HasOne("talim_platforma.Models.Kurs", "Kurs")
                        .WithMany("Guruhlar")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Oqituvchi")
                        .WithMany()
                        .HasForeignKey("OqituvchiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Oqituvchi");
                });

            modelBuilder.Entity("talim_platforma.Models.Imtihon", b =>
                {
                    b.HasOne("talim_platforma.Models.Guruh", "Guruh")
                        .WithMany()
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Oqituvchi")
                        .WithMany()
                        .HasForeignKey("OqituvchiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Guruh");

                    b.Navigation("Oqituvchi");
                });

            modelBuilder.Entity("talim_platforma.Models.ImtihonNatija", b =>
                {
                    b.HasOne("talim_platforma.Models.Imtihon", "Imtihon")
                        .WithMany()
                        .HasForeignKey("ImtihonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Imtihon", null)
                        .WithMany()
                        .HasForeignKey("ImtihonId1");

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imtihon");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.ImtihonSavol", b =>
                {
                    b.HasOne("talim_platforma.Models.Imtihon", "Imtihon")
                        .WithMany("Savollar")
                        .HasForeignKey("ImtihonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imtihon");
                });

            modelBuilder.Entity("talim_platforma.Models.Kurs", b =>
                {
                    b.HasOne("talim_platforma.Models.Sertifikat", "Sertifikat")
                        .WithMany()
                        .HasForeignKey("SertifikatId");

                    b.Navigation("Sertifikat");
                });

            modelBuilder.Entity("talim_platforma.Models.Sertifikat", b =>
                {
                    b.HasOne("talim_platforma.Models.Imtihon", "Imtihon")
                        .WithMany()
                        .HasForeignKey("ImtihonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imtihon");

                    b.Navigation("Kurs");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.TalabaGuruh", b =>
                {
                    b.HasOne("talim_platforma.Models.Guruh", "Guruh")
                        .WithMany("TalabaGuruhlar")
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guruh");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.TalabaKurs", b =>
                {
                    b.HasOne("talim_platforma.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Talaba");
                });

            modelBuilder.Entity("talim_platforma.Models.Tolov", b =>
                {
                    b.HasOne("talim_platforma.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("talim_platforma.Models.Foydalanuvchi", "Talaba")
                        .WithMany()
                        .HasForeignKey("TalabaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("talim_platforma.Models.TalabaKurs", "TalabaKurs")
                        .WithMany()
                        .HasForeignKey("TalabaKursId");

                    b.Navigation("Kurs");

                    b.Navigation("Talaba");

                    b.Navigation("TalabaKurs");
                });

            modelBuilder.Entity("talim_platforma.Models.Foydalanuvchi", b =>
                {
                    b.Navigation("OqituvchiDavomatlar");

                    b.Navigation("TalabaDavomatlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Guruh", b =>
                {
                    b.Navigation("Darslar");

                    b.Navigation("Davomatlar");

                    b.Navigation("TalabaGuruhlar");
                });

            modelBuilder.Entity("talim_platforma.Models.Imtihon", b =>
                {
                    b.Navigation("Savollar");
                });

            modelBuilder.Entity("talim_platforma.Models.Kurs", b =>
                {
                    b.Navigation("Guruhlar");
                });

            modelBuilder.Entity("talim_platforma.Models.FoydalanuvchiToliqMalumoti", b =>
                {
                    b.Navigation("Foydalanuvchi")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

